### ISSUE TITLE
Ubuntu系统装好一切后运行提示“未找到diskutil命令”

### ISSUE THREAD

**Issue by Sakakibara-Hu** [zk4/baiduFuse#1]
`./x.sh: 行 5: diskutil: 未找到命令`
`x - INFO - - fuse 4 cloud driver -`
`x - DEBUG - readdirAsync: /`

**Comment by zk4** [comment]
> `./x.sh: 行 5: diskutil: 未找到命令`
> `x - INFO - - fuse 4 cloud driver -`
> `x - DEBUG - readdirAsync: /`

这个命令是 Mac 上卸载挂载卷用的. 在 linux 上应该是  unmount
将  x.sh  里
``` bash
diskutil unmount force  ../mnt2
```
改成 
``` bash
sudo umount -f  ../mnt2
```
