### ISSUE TITLE
windows下挂载后无法读取文件内容

### ISSUE THREAD

**Issue by amstc** [zk4/baiduFuse#2]
能进盘符并正确显示文件列表和文件尺寸，但似乎无法读取文件内容，任何文件打开全是空白，复制到本地会占用正确的容量，打开也是空白。列目录的时候不停地报这行错误：

scheduler:61 - INFO - mmap slice assignment is wrong size

比如一个文件夹有10个文件，就会显示10次这个wrong size错误

**Comment by zk4** [comment]
我没 windows 环境. 一直都没有很好支持,只能说理论可用. 
百度 rest 接口已基本不可用. 时常抽风.  已经有一个新思路.  等更新吧.

**Comment by amstc** [comment]
好的

**Comment by glide-the** [comment]
arch manjaro 也遇到了同样的问题 
![image](https://user-images.githubusercontent.com/16206043/82651169-5ffcb300-9c4e-11ea-8a6b-4b307ef0aad8.png)
