### ISSUE TITLE
arch manjaro 链接成功百度网盘，无法下载文件

### ISSUE THREAD

**Issue by glide-the** [zk4/baiduFuse#3]
manjaro 下显示输出如下
scheduler:61 - INFO - mmap slice assignment is wrong size

**Comment by glide-the** [comment]
测试之后发现只是相应的文件信息没有正常显示，相关执行文件是可以正常执行
![image](https://user-images.githubusercontent.com/16206043/82652851-e2867200-9c50-11ea-9d80-e3d3474d2b98.png)

**Comment by zk4** [comment]
@glide-the 
能用就好.
mmap slice assignment is wrong size , 应该是拿的大小跟实际大小不一样. 

通过百度 api 拿流的方案我准备放弃了.   稍微调几次接口, 百度盘那边分分钟给你返 user unauthorized . 
简直坑,  现在有个更好的方案.  完全可以规避这个问题.

**Comment by glide-the** [comment]
很想发个狗头的图片，但是没找到。。。那种黄晃晃的
